# Generated by Django 4.1.2 on 2022-11-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reported',
            name='Reference_Number',
            field=models.CharField(blank=True, default='3ee06598-7', max_length=100, unique=True),
        ),
    ]
