# Generated by Django 4.1.2 on 2022-11-02 03:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0002_alter_reported_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reported',
            name='Reference_Number',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
