# Generated by Django 4.1.2 on 2022-11-03 04:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0003_alter_reported_reference_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forwarded2Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference_Number', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('personreported', models.CharField(max_length=100)),
                ('tribe', models.CharField(max_length=100)),
                ('Telephone_Number', models.CharField(max_length=100)),
                ('Residence', models.CharField(max_length=100)),
                ('Officerincharge', models.CharField(blank=True, max_length=100)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(blank=True, max_length=5000)),
                ('CrimeScene', models.CharField(blank=True, max_length=100)),
                ('Penalty', models.CharField(blank=True, max_length=5000)),
            ],
        ),
    ]
