# Generated by Django 4.1.2 on 2022-11-03 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0004_forwarded2court'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reported',
            name='Penalty',
        ),
        migrations.RemoveField(
            model_name='reported',
            name='Status',
        ),
    ]
