# Generated by Django 4.1.2 on 2022-11-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0006_alter_forwarded2court_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwarded2court',
            name='CrimeScene',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='forwarded2court',
            name='Officerincharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='forwarded2court',
            name='Residence',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='forwarded2court',
            name='Telephone_Number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='forwarded2court',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='forwarded2court',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='forwarded2court',
            name='personreported',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='forwarded2court',
            name='tribe',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
