# Generated by Django 4.1.2 on 2022-11-04 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0008_alter_forwarded2court_reference_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forwarded2Court',
        ),
    ]
