# Generated by Django 4.1.2 on 2022-11-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0010_forwarded2court'),
    ]

    operations = [
        migrations.AddField(
            model_name='reported',
            name='Status',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
