# Generated by Django 4.1.2 on 2022-11-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0011_reported_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reported',
            name='CourtStatus',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
